version: '3.1'

services:
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: saber.devent.kr
      LETSENCRYPT_HOST: saber.devent.kr
      LETSENCRYPT_EMAIL: hhj@devent.kr
    network_mode: "bridge"